Fix NPM dependencies
Seems that the package.json file was out of sync because of a typo. I was
receiving this error when running `npm run build` after `npm install`:

```
Error: Cannot find module 'underscore' from '/Users/msegreto/Developement/openFEC-web-app/static/js/modules'
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)

npm ERR! openfec-web-app@0.0.0 build: `browserify static/js/init.js > static/js/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openfec-web-app@0.0.0 build script.
npm ERR! This is most likely a problem with the openfec-web-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify static/js/init.js > static/js/app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls openfec-web-app
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "build"
npm ERR! cwd /Users/msegreto/Developement/openFEC-web-app
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/msegreto/Developement/openFEC-web-app/npm-debug.log
npm ERR! not ok code 0
```

After my change I can `npm install` and `npm run build` and it works.

Please inform me if any of the dependencies in that file are out of date
and no longer required.